# Generated by Django 4.0.3 on 2022-04-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='boardCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('cpm', models.IntegerField()),
                ('helmet', models.BooleanField()),
                ('service', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
                ('app_dl', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CountryData',
        ),
    ]
