# Generated by Django 4.0.3 on 2022-04-14 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_boardcost_delete_countrydata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardcost',
            options={'verbose_name_plural': '업체별 시간당 가격'},
        ),
    ]
