# Generated by Django 4.0.3 on 2022-04-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_boardcost_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('cost', models.IntegerField(db_column='Cost')),
                ('cpm', models.IntegerField(db_column='Cpm')),
                ('helmet', models.CharField(blank=True, max_length=5, null=True)),
                ('serv', models.CharField(blank=True, max_length=50, null=True)),
                ('site', models.CharField(blank=True, db_column='Site', max_length=50, null=True)),
                ('app_dl', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='boardCost',
        ),
    ]
