# Generated by Django 4.0.3 on 2022-04-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_service_delete_boardcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('cpm', models.IntegerField()),
                ('cost_0min', models.IntegerField()),
                ('cost_5min', models.IntegerField()),
                ('cost_10min', models.IntegerField()),
                ('cost_15min', models.IntegerField()),
                ('cost_20min', models.IntegerField()),
                ('cost_25min', models.IntegerField()),
                ('cost_30min', models.IntegerField()),
            ],
            options={
                'db_table': 'Costs',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
