# Generated by Django 4.0.3 on 2022-04-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_costs_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('yy', models.IntegerField(primary_key=True, serialize=False)),
                ('ac_case', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('injured', models.IntegerField()),
            ],
            options={
                'db_table': 'accident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_type', models.CharField(max_length=20)),
                ('ac_detail', models.CharField(max_length=50)),
                ('ac_case', models.IntegerField()),
                ('ac_per', models.IntegerField()),
            ],
            options={
                'db_table': 'acc_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SafetyRule',
            fields=[
                ('rule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('follow_rule_case', models.IntegerField(blank=True, null=True)),
                ('follow_rule_per', models.IntegerField(blank=True, null=True)),
                ('not_follow_rule_case', models.IntegerField(blank=True, null=True)),
                ('not_follow_rule_per', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'safety_rule',
                'managed': False,
            },
        ),
    ]
